server:
  port: 8080
  error:
    include-stacktrace: never

#logging:
#  level:
#    #    ROOT: DEBUG
#    com.socgen.loanapprovalplatform: DEBUG
#
spring:
  #  profiles:
  #    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/LoanApprovalPlatForm
    username: kartik.m
    password:

keycloak:
  realm: carloan
  auth-server-url: http://localhost:9080/auth
  ssl-required: external
  resource: internal
  credentials:
    secret: 91e20d8f-1678-4d04-8782-f04e1bc19219
  use-resource-role-mappings: true
  bearer-only: true


