#logging:
#  level:
#    ROOT: DEBUG
#    com.socgen.loanapprovalplatform: DEBUG

spring:
  application:
    name: LoanApprovalPlatForm
  profiles:
    active: dev



  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  liquibase:
    change-log: classpath:config/liquibase/master.xml

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"