

#logging:
#  level:
#    ROOT: DEBUG
#    com.socgen.loanapprovalplatform: DEBUG

spring:
  profiles:
    active: default

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa


server:
  port: 8080