#logging:
#  level:
#    ROOT: DEBUG
#    com.socgen.loanapprovalplatform: DEBUG

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  liquibase:
    change-log: classpath:config/liquibase/master.xml

  jpa:
    hibernate:
      ddl-auto: none
#    enabled: true
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    user: sa
#    password: sa
#    changeLog: classpath:config/liquibase/changelog/00000000000000_initial_schema.xml


server:
  port: 8080