global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'loanapprovalplatform'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
#      Change your host IP address
      - targets: ['192.168.0.6:8080']