version: '2'
services:
  loanapprovalplatform-app:
    image: loanapprovalplatform
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://loanapprovalplatform-postgresql:5432/LoanApprovalPlatForm
      - SPRING_DATASOURCE_USERNAME=LoanApprovalPlatForm
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:9080/auth
      - KEYCLOAK_REALM=carloan
      - KEYCLOAK_CREDENTIALS_SECRET=91e20d8f-1678-4d04-8782-f04e1bc19219
      - KEYCLOAK_RESOURCE=internal
      - STARTUP_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080

  loanapprovalplatform-postgresql:
    extends:
      file: postgresql.yml
      service: loanapprovalplatform-postgresql
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
